# Generated by Django 6.0 on 2026-01-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_privatemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static/media/images/avatar.svg', null=True, upload_to='images/'),
        ),
    ]
