# Generated by Django 5.2.8 on 2026-04-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
    ]
